### ISSUE TITLE
Highlights only work with -nick, not -word

### ISSUE THREAD

**Issue by Zannick** [murgo/IrssiNotifier#165]
The IrssiNotifier script doesn't recognize inlined highlights (namely, those set up as -word instead of -nick) and thus never sends those notifications. The result is that I'm never notified for channel highlights because all my highlights use -word.

I use hilightwin.pl, so perhaps it could be configurable to trip notify whenever the hilight window has a new entry (other than "Day changed")?

On the other hand, hilightwin.pl can recognize -word highlights (via `($dest->{level} & (MSGLEVEL_HILIGHT))`), so I should think irssinotifier.pl should be able to as well.

**Comment by murgo** [comment]
Not sure if this works as supposed based on #178.
