### ISSUE TITLE
irssi notifier irssi script shows wget output

### ISSUE THREAD

**Issue by bsdlp** [murgo/IrssiNotifier#174]
I'm running the latest version of the irssinotifier.pl script, and on notifiable events my irssi client will display the wget progress bar and other wget output.

```
[jchen@55fa15ae2cf1 ~]$ wget --version
GNU Wget 1.16.2 built on linux-gnu.
```

**Comment by ailin-nemui** [comment]
http://savannah.gnu.org/bugs/?44403

**Comment by murgo** [comment]
I'm guessing that it was caused by the bug in the link above. If this problem is still ongoing, feel free to reopen the ticket.
