### ISSUE TITLE
Modernize

### ISSUE THREAD

**Issue by murgo** [murgo/IrssiNotifier#182]
This might be needed to break down to couple of issues.

1) Update dependencies. At least google services (gcm) and licensing services, maybe google auth.

2) Update UI. Use AppCompat instead of ActionBarSherlock. Maybe change main screen into RecyclerView. Use Material UI.

3) Update server. New InstanceId based messages, also add device grouping.

4) Bump SdkVersions.

**Comment by Cykyter** [comment]
1) Updating to newer GCM might be problematic as Google is shifting towards Firebase Cloud Messaging (FCM). With announcement of FCM Google also says that GCM will be depreciated in future.

**Comment by blunden** [comment]
@Cykyter Based on what I've read, it seems like GCM 3.0 will be supported for the forseeable future, it just won't get any new features. I still use GCM 3.0 in one of my apps and currently have no plans to change it since it currently provides no benefits for that app's use case and it already works well.

**Comment by stwalkerster** [comment]
As a heads-up, the [GCM help pages](https://developers.google.com/cloud-messaging/android/android-migrate-fcm) show:
> The GCM server and client APIs are deprecated and will be removed as soon as April 11, 2019.

**Comment by murgo** [comment]
Oh damn, I totally forgot that PR @cyky sent two years ago, back then I didn't merge it because I didn't have time to test and deploy everything and since everything kind of worked already I just didn't get to it.

Now with the Pie problem I might actually use the stuff :)

**Comment by murgo** [comment]
Some of these are now done like Firebase upgrade, dependency upgrade, getting rid of ActionBarSherlock. Some are old specs. Some stuff is missing like DefaultHttpClient or whatever being deprecated etc.
