### ISSUE TITLE
Channel notifications 

### ISSUE THREAD

**Issue by varazir** [murgo/IrssiNotifier#186]
I would love to have a notification when a channel get highlighted

**Comment by murgo** [comment]
Umm, what do you mean? Like if someone says the channel name?

**Comment by ledakis** [comment]
Maybe @varazir means when there is activity in a channel (and as a result gets highlighted in the bottom bar in irssi).
I am also after this. Got an almost silent channel and want to get notifications if someone talks in that channel only.

**Comment by varazir** [comment]
@murgo No when someone say something in the channel.

@ledakis ya what's I'm looking for

**Comment by d7415** [comment]
You can make irssi highlight on any message in a channel. `/hilight -mask -channels #test *` should do it.

**Comment by varazir** [comment]
@d7415 I tried that but it didn't work. + Purple Hangouts plugin for Bitlbee has support for group chats, it creates a new channel so I can't keep adding a highlight for each( if it had worked)

**Comment by d7415** [comment]
Interesting. That worked when I tested it. It might help @ledakis anyway. It's possible that it'd even work without the `-channels #test` part which would highlight on everything, but that might make an irssi dev cry...

**Comment by ledakis** [comment]
Yes it has worked for me, thanks @d7415!

**Comment by varazir** [comment]
Strange, I have to look into why it's not working for me. @ledakis so you have any  scripts irssinotification ofc ? Can you post your ignore/hide settings?

**Comment by ledakis** [comment]
I have [elist](https://github.com/irssi/scripts.irssi.org/blob/gh-pages/scripts/elist.pl) only.
On that particular channel I am ignoring JOINS PARTS QUITS NICKS.
And have highlighted the channel with the command above by @d7415 .

**Comment by varazir** [comment]
@ledakis I have a lot more, autochannel,crapbuster,smartfilter,hide and some others but I don't think they will affect this.

**Comment by varazir** [comment]
Removed the scripts still I can't get anything to be highlighted in the channel... it's a irssi problem more so I'm going to ask in #irssi

**Comment by varazir** [comment]
I solved the higlighting problem. I hadn't set it to highlight PUBLIC level. case closed.
