### ISSUE TITLE
Unable to register with GCM under Nougat

### ISSUE THREAD

**Issue by kassidy** [murgo/IrssiNotifier#191]
After updating my phone to Nougat 7.1 I noticed that I wasn't getting notifications from IRSSI Notifier. 
I attempted a de-registration and registration, and I now receive the following when clicking on my Google account in the options to select
"Unable to register to GCM! Please try again later!"

**Comment by murgo** [comment]
Can you try removing the app and reinstalling it from Google Play?

Or at least try to remove all data and cache from the app.

ti 29. mar 2016 klo 17.05 kassidy <notifications@github.com> kirjoitti:

**Comment by kassidy** [comment]
Aha.
I tried clearing cache and data, that didn't work. Did a reinstall from Store and now it's hooking into GCM and working again.

Thank you! And as of a few minutes ago you have another paying customer, just upgraded to Plus. ;)
