### ISSUE TITLE
Alternative download source

### ISSUE THREAD

**Issue by IzzySoft** [murgo/IrssiNotifier#193]
Is there an alternative source to get the `.apk` outside of Playstore? Maybe you could attach it to the corresponding `releases/`?

**Comment by murgo** [comment]
Currently no, since the app is heavily dependant of google services anyway (uses google account for authenticating, uses google cloud messaging for push notifications).

**Comment by IzzySoft** [comment]
I run Google-free here, but still can meet that. Thanks to microG (the open-source GMS replacement), GCM works like a breeze. Though I have to admit I don't remember if I ever used Google Account for authenticating – but AFAIR that's also available.

Of course I'd accept a "No" if you still insist, but a "Yes" would be nice :wink:

**Comment by murgo** [comment]
The latest IrssiNotifier version 1.9.0 (just fresh out of the oven) can be downloaded as APK from Github, under releases tab. It's not the official way to get the package but maybe it will help you.

**Comment by IzzySoft** [comment]
The "tin foil fraction" is calling it a devil (it would definitely be a show-stopper for F-Droid – but then, so would be GMS which your app also uses). Firebase Analytics is considered a privacy risk, a.o. because its collected data end up in the "Google pool". Being closed source, noone but Google can say what's really collected. If switching that out would be an option for you, but you somehow need some analytics: what's widely accepted in the FOSS world (even on F-Droid) is ACRA. Not being a dev, I cannot tell how it compares feature-wise, though.
